theme: jekyll-theme-minimal
title: Between the Lines
description: A repository for sharing data, tools and info related to my 
  research on using character interaction networks to examine gendered 
  character positions in popular film narratives.
logo: /assets/img/logo.png